eureka:
  client:
    register-with-eureka: false

server:
  port: 7075

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Project-service
          uri: lb://PROJECT-SERVICE  # ✅ Use service name if using Eureka
          predicates:
            - Path=/project/**
        - id: Company-service
          uri: lb://COMPANY-SERVICE  # ✅ Use service name if using Eureka
          predicates:
            - Path=/company/**
        - id: Employee-service  # ✅ Fixed indentation
          uri: lb://EMPLOYEE-SERVICE  # ✅ Fixed service name case
          predicates:
            - Path=/employee/**

management:
  tracing:
    sampling:
      probability: 1.0
