eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
spring:
  application:
    name: Employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: Reddy-333@
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
